# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 3000, host: 53000 # Rails
  config.vm.provider "virtualbox" do |vb|
    vb.name = "rug-cap_demo"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
